### PR TITLE
color sequence button with the color found in config file

### PR DESCRIPTION
**Pull request by Houston4444**
Screenshot_seq192_colors

Enable to set a color for instrument in config file, for faster identification.

Config file example:
```
{
    "buses": {
        "0": {
            "name": "Sampler",
            "channels": {
                "0": {
                    "name": "Drums",
                    "notes": {"36": "Kick", "37": "Snare", "38": "Snare flam", "39": "Snare side stick", "40": "Snare roll", "41": "Snare rim shot", "42": "Snare drag", "44": "HH1 closed", "45": "HH1 open", "46": "HH1 pedal", "47": "Hats2 crash", "48": "Hats2 bell", "49": "Hats2 shack", "50": "Tom 10\"", "51": "Tom 10\" flam", "52": "Tom 13\"", "53": "Tom 13\" flams", "54": "Ride 22\"", "55": "Ride 22\" bell", "56": "Splash 6\"", "57": "Splash 6\" choke", "58": "Crash 14\"", "59": "Crash 18\" choke", "60": "Crash 18\""},
                    "controls": {
                        "1": "Custom cc name ",
                        "2": "Etc"
                    }
                },
                "1": {
                    "name": "DrumsElectro",
                    "color": "maroon",
                    "notes": {"36": "Kick 1", "37": "Kick 2", "38": "Kick 3", "39": "Snare", "40": "Clap 1", "41": "Clap 2", "44": "Closed HH 1", "45": "Closed HH 2", "46": "Closed HH 3", "47": "Closed HH 4", "48": "Open HH", "49": "Side HH", "50": "Side OHH", "51": "Zap 1", "52": "Zap 2", "53": "FX"},
                    "controls": {
                        "1": "Custom cc name ",
                        "2": "Etc"
                    }
                },
                "2": {
                    "color" : "#9040ff"
                }
            }
        },
        "1": {
            "name": "Bass synth",
            "channels":{
                "0": {"name": "Trap bass"},
                "1": {"name": "Wobble"}
            }
        }
    }
}
```

This applies the color on the sequence button with an alpha channel to 0.125 (set transparency in the color in the config file has no effect). I don't know if this ratio is the best, it is hard to know because it depends a lot of the screen quality.
Normally, user should still recognize an active/passive/recording sequence.

### CODE REVIEW

**Comment by jean-emmanuel** [comment]
Good idea ! I test and fiddle with it soon.

**Comment by Houston4444** [comment]
Another approach would be to set the color only on the top part of the sequence button, where text is drawn, or only on the events parts (but I tested the second and I think result is quite strange). Set the color on top seems to be nice, impossible to have colors where sequence state is not clear with that, and we can set more opacity.

I also wanted to color the background of the input field in the editor window, where "Bus: Instrument" is written, but I don't know how to do this exactly (I did not search a long time, it's true ;)).

**Comment by Houston4444** [comment]
I changed this to only apply the color on the header part of the sequence button, I find it more readable this way, whatever the color is. The opacity is set to 0.4 here.
Screenshot_seq192_label_colored

**Comment by jean-emmanuel** [comment]
It feels a bit visually intrusive to me, I'll try something more subtle, like a 2px border on the top of the box.

**Comment by jean-emmanuel** [comment]
Merged with additional tweaks and changes.

**Comment by Houston4444** [comment]
thanks a lot.
Très classe le résultat, j'aime beaucoup.

**Pull request merged**
