### PR TITLE
Fixed makefile install

### PR DESCRIPTION
**Pull request by redtide**
I guess this should be correct to build the PKGBUILD Archlinux package.
You can remove the PKGBUILD on the repository, it's not necessary to maintain it there, I will do on AUR git, if you are registered there you can do it as well.

### CODE REVIEW

**Comment by jean-emmanuel** [comment]
I'm not sure PREFIX should be applied to files that go in /usr/share, do you have an example that suggests that ? DESTDIR is definitely missing from the last install command though.

**Comment by redtide** [comment]
I need to "install" the files in a directory to be able to package them, that is the way `makepkg` uses to build packages using the `PKGBUILD` script. Hardcoding `/usr/share` makes it impossible to do.
I'm not much an autotools user, I just guess that the prefix for the installation should be the same for all files.

**Comment by redtide** [comment]
Anyway, the package works now with last changes and I pushed it at <https://aur.archlinux.org/packages/seq192-git/>, if you want you can close this.

**Comment by jean-emmanuel** [comment]
You're right, PREFIX should be applied everywhere actually, thanks !

**Pull request merged**
