### PR TITLE
Added backspace to remove notes on editor

### PR DESCRIPTION
**Pull request by CarloCattano**
Just a tiny addition to emulate most software around , and beacuse DEL key its quite tiny and far on my current laptop :-)

### CODE REVIEW

**Comment by jean-emmanuel** [comment]
Thanks ! The key should be checked here as well to avoid breaking text inputs: https://github.com/jean-emmanuel/seq192/blob/a55e8617bdb324955972d45441b5d0bb22fa3639/src/gui/editwindow.cpp#L558

**Comment by jean-emmanuel** [comment]
could you please remove .vscode/ and json/ from the repo and push again ?  `git rm --cached .vscode && git rm --cached json`

**Comment by jean-emmanuel** [comment]
could you please remove .vscode/ and json/ from the repo and push again ?  `git rm --cached .vscode && git rm --cached json`

**Comment by jean-emmanuel** [comment]
could you please remove .vscode/ and json/ from the repo and push again ?  `git rm --cached .vscode && git rm --cached json`

**Comment by CarloCattano** [comment]
Should be good to go

**Pull request merged**
